
desc "Setup Library (sudo)"
task :init do
  dist = `uname -v`
  dist.downcase!
  aptget = `which apt-get`
  yum    = `which yum`
  if(aptget.size > 0)then
    ## Ubuntu
    sh "sudo -E apt-get -y install g++ make cmake libuv-dev libssl-dev"
  elsif(yum.size > 0)then
    #### Centos
    sh "sudo -E yum -y install cassandra-cpp-driver cassandra-cpp-driver-devel"
  else
    puts "[ERROR] Unsupported OS"
  end
  sh "git clone https://github.com/datastax/cpp-driver.git"
  sh "mkdir cpp-driver/build"
  sh "cd cpp-driver/build"
  sh "cmake .."
  sh "make"
  sh "sudo -E make install"
end

desc "Build Cassandra Runner (CXX)"
task :build do
  aptget = `which apt-get`
  yum    = `which yum`
  if(aptget.size > 0)then
    sh "ruby extconf_ubuntu.rb"
  elsif(yum.size > 0)then
    sh "ruby extconf.rb"
  end
  sh "make"
end

desc "Simple Test"
task :test => [:build] do
  #sh "cd test; make test dtest"
  #sh "ruby test/test.rb"
  sh "ruby test/test02.rb"
end

task :clean do
  if(File.exist?("Makefile"))then
    sh "make clean"
  end
  sh "cd test; make clean"
end

task :distclean => [:clean] do
  sh "rm -vf Makefile"
end

