
desc "Setup Library (sudo)"
task :init do
  dist = `uname -v`
  dist.downcase!
  aptget = `which apt-get`
  yum    = `which yum`
  if(aptget.size > 0)then
    ## Ubuntu
    if(dist.include?("ubuntu"))then
        sh "sudo apt-get -y install g++ make cmake libuv-dev libssl-dev"
    else
      ## Dockerfile
      sh "apt-get -y install g++ make cmake libuv-dev libssl-dev"
    end
    sh "git clone https://github.com/datastax/cpp-driver.git"
    sh "mkdir cpp-driver/build"
    sh "cd cpp-driver/build"
    sh "cmake .."
    sh "make"
    if(dist.include?("ubuntu"))then
      sh "sudo make install"
    else
    ## Dockerfile
      sh "make install"
    end
  elsif(yum.size > 0)then
    #### Centos
    if(dist.include?("centos"))then
      sh "sudo yum -y install cassandra-cpp-driver cassandra-cpp-driver-devel"
    else
      sh "yum -y install cassandra-cpp-driver cassandra-cpp-driver-devel"
    end
  else
    puts "[ERROR] Unsupported OS"
  end
end

desc "Build Cassandra Runner (CXX)"
task :build do
  dist = `uname -v`
  dist.downcase!
  aptget = `which apt-get`
  yum    = `which yum`
  if(dist.include?("ubuntu") or aptget.size > 0)then
    sh "ruby extconf_ubuntu.rb"
  elsif(dist.include?("centos") or yum.size > 0)then
    sh "ruby extconf.rb"
  end
  sh "make"
end

desc "Simple Test"
task :test => [:build] do
  #sh "cd test; make test dtest"
  #sh "ruby test/test.rb"
  sh "ruby test/test02.rb"
end

task :clean do
  if(File.exist?("Makefile"))then
    sh "make clean"
  end
  sh "cd test; make clean"
end

task :distclean => [:clean] do
  sh "rm -vf Makefile"
end

